name: CI

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - github-actions
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test-hackatom-in-singlepass-vm:
    name: Rust nightly on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: macOS
            os: macOS-latest
    defaults:
      run:
        shell: bash
        working-directory: ./contracts/hackatom
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            '**/target'
          key: ${{ matrix.os }}-xx-${{ hashFiles('**/Cargo.lock') }}
      - name: Build / Test hackatom wasm
        run: |
          cargo wasm --locked
          cargo integration-test --no-default-features --features singlepass --locked
